1.   **Upload the data (Excel Sheet) given for this assignment to the google drive.**
2.   **Mount the google drive by giving required permissions.**
3.   **Enter the permission code in the field that appears after running the code section in the first cell.**



In [112]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


**Import all the required Modules**

In [113]:
import pandas as pd
import numpy as np

1.  **Load the file using pandas**
2.  **Check the file using head() method**

In [114]:
dataset = pd.read_excel("My Drive/CV_asgnmnt1_Data.xlsx")

dataset.head()


wavelength_L nm           x  ...  silvania_spectra  uniform_spectra
0                360  0.000006  ...          0.021798                1
1                365  0.000011  ...          0.025739                1
2                370  0.000019  ...          0.029357                1
3                375  0.000035  ...          0.031511                1
4                380  0.000064  ...          0.035863                1

[5 rows x 7 columns]

1.  **As we are considering a true white object, its reflectance will be unity. So, the radiance will become equal to illuminance.**
2.  **Now considering one of the illuminance spectra as given in the assignment,
we will calculate the tristumulus values, i.e. X , Y and Z.**
3.  **Let us consider the *philips_spectra* first.**

In [115]:
# Integral
X = sum(dataset['philips_spectra']*dataset['x'])
Y = sum(dataset['philips_spectra']*dataset['y'])
Z = sum(dataset['philips_spectra']*dataset['z'])
TristumulusValues = [X,Y,Z]
np.array(TristumulusValues)

array([0.29222667, 0.2416636 , 0.06175656])

1.  **GIVEN MATRIX**
2.  **Finding the inverse of the matrix**

In [116]:
A = [[0.49,0.31,0.2],[0.177,0.813,0.01],[0,0.01,0.99]]
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 2.36439757, -0.89578988, -0.46860769],
       [-0.51482211,  1.42521374,  0.08960837],
       [ 0.00520022, -0.0143961 ,  1.00919588]])

**This code section gives the normalized values of RGB colors.**

In [117]:
np.dot(A_inverse,TristumulusValues)

array([0.44552062, 0.19951144, 0.0603651 ])

**This code section gives the RGB representation of a true white object under philips_spectra illuminance.**

In [118]:
R = 255*np.dot(A_inverse,TristumulusValues)[0]
G = 255*np.dot(A_inverse,TristumulusValues)[1]
B = 255*np.dot(A_inverse,TristumulusValues)[2]
print("Red =",R)
print("Green =",G)
print("Blue =",B)

Red = 113.60775919058099
Green = 50.8754179227766
Blue = 15.393100008143158


**Now Let us consider the *silvania_spectra* and calculate the tristumulus values for this spectrum.**

In [119]:
X = sum(dataset['silvania_spectra']*dataset['x'])
Y = sum(dataset['silvania_spectra']*dataset['y'])
Z = sum(dataset['silvania_spectra']*dataset['z'])
TristumulusValues = [X,Y,Z]
np.array(TristumulusValues)

array([0.48411658, 0.44159457, 0.13298113])

**This code section gives the normalized values of the RGB color components of a true white object under silvania_spectra**

In [120]:
np.dot(A_inverse,TristumulusValues)

array([0.68675213, 0.39204896, 0.13036428])

**This code section gives the RGB representation of a true white object under silvania_spectra illuminance.**

In [121]:
R = 255*np.dot(A_inverse,TristumulusValues)[0]
G = 255*np.dot(A_inverse,TristumulusValues)[1]
B = 255*np.dot(A_inverse,TristumulusValues)[2]
print("Red =",R)
print("Green =",G)
print("Blue =",B)

Red = 175.12179229596404
Green = 99.9724847224213
Blue = 33.24289207793977


**Now Let us consider the uniform_spectra and calculate the tristumulus values for this spectrum.**

In [122]:
X = sum(dataset['uniform_spectra']*dataset['x'])
Y = sum(dataset['uniform_spectra']*dataset['y'])
Z = sum(dataset['uniform_spectra']*dataset['z'])
TristumulusValues = [X,Y,Z]
np.array(TristumulusValues)

array([1.00000009, 0.99999984, 1.00000009])

**This code section gives the normalized values of the RGB color components of a true white object under uniform_spectra**

In [123]:
np.dot(A_inverse,TristumulusValues)

array([1.00000032, 0.99999973, 1.0000001 ])

**This code section gives the RGB representation of a true white object under uniform_spectra illuminance.**

In [124]:
R = round(255*np.dot(A_inverse,TristumulusValues)[0],3)
G = round(255*np.dot(A_inverse,TristumulusValues)[1],3)
B = round(255*np.dot(A_inverse,TristumulusValues)[2],3)
print("Red =",R)
print("Green =",G)
print("Blue =",B)

Red = 255.0
Green = 255.0
Blue = 255.0
