1.  **Upload the data (Excel Sheet) given for this assignment to the google drive.**
2.  **Mount the google drive by giving required permissions.**
3.  **Enter the permission code in the field that appears after running the code section in the first cell.**

In [45]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


**Import all the required Modules**

In [46]:
import pandas as pd
import numpy as np

1. **Load the file using pandas**
2.  **Check the file using head() method**

In [47]:
dataset = pd.read_excel("My Drive/CV_asgnmnt1_Data.xlsx")

dataset.head()


wavelength_L nm           x  ...  silvania_spectra  uniform_spectra
0                360  0.000006  ...          0.021798                1
1                365  0.000011  ...          0.025739                1
2                370  0.000019  ...          0.029357                1
3                375  0.000035  ...          0.031511                1
4                380  0.000064  ...          0.035863                1

[5 rows x 7 columns]

**Calculation of radiance for X, Y, Z**

In [48]:
reflectance_X = dataset['x']/max(dataset['x'])
radiance_X = dataset['uniform_spectra']*reflectance_X
reflectance_Y = dataset['y']/max(dataset['y'])
radiance_Y = dataset['uniform_spectra']*reflectance_Y
reflectance_Z = dataset['z']/max(dataset['z'])
radiance_Z = dataset['uniform_spectra']*reflectance_Z

**Calculation of Tristumulus values**

In [54]:
 X = sum(radiance_X*dataset['x'])
 Y = sum(radiance_Y*dataset['y'])
 Z = sum(radiance_Z*dataset['z'])
 tristumulusValues = [X,Y,Z]
 np.array(tristumulusValues)

array([0.63402499, 0.72249052, 0.7367702 ])

**Calculation of the inverse of the matrix that is used for the conversion between RGB and XYZ model**

In [55]:
A = [[0.49,0.31,0.2],[0.177,0.813,0.01],[0,0.01,0.99]]
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 2.36439757, -0.89578988, -0.46860769],
       [-0.51482211,  1.42521374,  0.08960837],
       [ 0.00520022, -0.0143961 ,  1.00919588]])

**This code section gives the normalized values of the RGB color components of given object under uniform_spectra**

In [60]:
np.dot(A_inverse,tristumulusValues)

array([0.50663127, 0.76931411, 0.73644147])

**This code section gives the RGB representation of given object under uniform_spectra illuminance.**

In [61]:
R = 255*np.dot(A_inverse,tristumulusValues)[0]
G = 255*np.dot(A_inverse,tristumulusValues)[1]
B = 255*np.dot(A_inverse,tristumulusValues)[2]
print("Red =",R)
print("Green =",G)
print("Blue =",B)

Red = 129.19097505347645
Green = 196.1750971840394
Blue = 187.79257556388146
